name: _linter
run-name: "_linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reusable-linter:
    uses: ulfiac/commons/.github/workflows/reusable_linter.yaml@daba73e646bfa1774f5b6d1114760ff1e382bd1c # v1.0.32
