name: deploy admin layer
run-name: deploy admin layer - ${{ github.event.inputs.terraform_action }}

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        default: plan
        description: terraform action
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice

permissions:
  contents: read
  id-token: write

jobs:
  deploy-admin-layer:
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      auth: oidc
      aws_region: us-east-2
      terraform_action: ${{ github.event.inputs.terraform_action }}
      terraform_layer: admin_layer
    secrets: inherit
