name: reusable tf action
run-name: tf action - ${{ inputs.terraform_action }}

on:
  workflow_call:
    inputs:
      auth:
        default: oidc
        required: false
        type: string
      aws_environment:
        default: aws_green
        required: false
        type: string
      dump_github_context:
        default: false
        required: false
        type: boolean
      terraform_action:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      auth:
        default: oidc
        options:
          - keys
          - oidc
        required: false
        type: choice
      aws_environment:
        default: aws_green
        required: false
        type: choice
        options:
          - aws_green
          - aws_purple
          - aws_mgmt
      terraform_action:
        default: plan
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice
      dump_github_context:
        default: false
        required: false
        type: boolean

env:
  TF_LOG: OFF
  TF_LOG_CORE: OFF
  TF_LOG_PROVIDER: OFF
  TF_LOG_PATH: ./terraform.log
  TF_VAR_oidc_role_to_assume: ${{ secrets.OIDC_ROLE_TO_ASSUME }}

permissions:
  contents: read
  id-token: write

jobs:
  terraform_action:
    name: "${{ inputs.terraform_action }}: ${{ inputs.aws_environment }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    environment: ${{ inputs.aws_environment }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: pwd

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false
      - run: terraform --version

      - run: aws --version

      - name: configure aws credentials with keys
        if: ${{ inputs.auth == 'keys' }}
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: configure aws credentials with oidc
        if: ${{ inputs.auth == 'oidc' }}
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-2

      - name: dump github context (script)
        if: ${{ inputs.dump_github_context }}
        env:
          CONTEXT_ENV: ${{ toJson(env) }}
          CONTEXT_GITHUB: ${{ toJson(github) }}
          CONTEXT_INPUTS: ${{ toJson(inputs) }}
          CONTEXT_JOB: ${{ toJson(job) }}
          CONTEXT_MATRIX: ${{ toJson(matrix) }}
          CONTEXT_NEEDS: ${{ toJson(needs) }}
          CONTEXT_RUNNER: ${{ toJson(runner) }}
          CONTEXT_STEPS: ${{ toJson(steps) }}
          CONTEXT_STRATEGY: ${{ toJson(strategy) }}
          CONTEXT_VARS: ${{ toJson(vars) }}
        run: ${{ github.workspace }}/scripts/dump_github_context.sh

      - run: terraform init
      - run: terraform validate

      - name: import bootstrap
        env:
          OIDC_ROLE_TO_ASSUME: ${{ secrets.OIDC_ROLE_TO_ASSUME }}
        run: ../scripts/import_bootstrap.sh

      - name: terraform plan
        if: ${{ inputs.terraform_action == 'plan' }}
        run: |
          terraform plan -out=./tfplan.binary
          echo -e "\n::notice::Plan details.\n"

      - name: terraform plan destroy
        if: ${{ inputs.terraform_action == 'plan destroy' }}
        run: |
          terraform plan -destroy -out=./tfplan.binary
          echo -e "\n::notice::Plan destroy details.\n"

      - name: show plan summary
        if : ${{ inputs.terraform_action == 'plan' || inputs.terraform_action == 'plan destroy' }}
        run: ../scripts/show_plan_summary.sh

      - name: terraform apply
        if: ${{ inputs.terraform_action == 'apply' }}
        run: |
          set -o pipefail
          terraform apply -auto-approve | tee tfapply.out
          echo -e "\n::notice::Apply details.\n"

      - name: terraform destroy
        if: ${{ inputs.terraform_action == 'destroy' }}
        run: |
          set -o pipefail
          terraform apply -destroy -auto-approve | tee tfdestroy.out
          echo -e "\n::notice::Destroy details.\n"

      - name: show apply summary
        if: ${{ inputs.terraform_action == 'apply' || inputs.terraform_action == 'destroy' }}
        run: ../scripts/show_apply_summary.sh "${{ inputs.terraform_action }}"
