name: reusable tf action
run-name: tf action - ${{ inputs.terraform_action }}

on:
  workflow_call:
    inputs:
      annotate_context_details:
        default: false
        required: false
        type: boolean
      auth:
        default: oidc
        required: false
        type: string
      aws_environment:
        default: aws_mgmt
        required: false
        type: string
      aws_region:
        default: us-east-2
        required: false
        type: string
      terraform_action:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      annotate_context_details:
        default: false
        required: false
        type: boolean
      auth:
        default: oidc
        options:
          - keys
          - oidc
        required: false
        type: choice
      aws_environment:
        default: aws_mgmt
        required: false
        type: choice
        options:
          - aws_mgmt
      aws_region:
        default: us-east-2
        required: false
        type: choice
        options:
          - us-east-2
          - us-west-2
      terraform_action:
        default: plan
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice

env:
  TF_LOG: OFF
  TF_LOG_CORE: OFF
  TF_LOG_PROVIDER: OFF
  TF_LOG_PATH: ./terraform.log
  TF_VAR_aws_region: ${{ inputs.aws_region }}
  TF_VAR_oidc_role_to_assume: ${{ vars.OIDC_ROLE_TO_ASSUME }}

permissions:
  contents: read
  id-token: write

jobs:
  terraform_action:
    name: "${{ inputs.terraform_action }}: ${{ inputs.aws_environment }} in ${{ inputs.aws_region }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    environment: ${{ inputs.aws_environment }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2, released 2026-01, checked 2026-03
      - run: pwd

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0, released 2026-02, checked 2026-03
        with:
          terraform_wrapper: false
      - run: terraform --version

      - run: aws --version

      - name: configure aws credentials with keys
        if: ${{ inputs.auth == 'keys' }}
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0, released 2026-02, checked 2026-03
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: configure aws credentials with oidc
        if: ${{ inputs.auth == 'oidc' }}
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0, released 2026-02, checked 2026-03
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.OIDC_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws_region }}

      - name: dump context (script)
        env:
          ANNOTATE: ${{ inputs.annotate_context_details }}
          CONTEXT_ENV: ${{ toJson(env) }}
          CONTEXT_GITHUB: ${{ toJson(github) }}
          CONTEXT_INPUTS: ${{ toJson(inputs) }}
          CONTEXT_JOB: ${{ toJson(job) }}
          CONTEXT_MATRIX: ${{ toJson(matrix) }}
          CONTEXT_NEEDS: ${{ toJson(needs) }}
          CONTEXT_RUNNER: ${{ toJson(runner) }}
          CONTEXT_STEPS: ${{ toJson(steps) }}
          CONTEXT_STRATEGY: ${{ toJson(strategy) }}
          CONTEXT_VARS: ${{ toJson(vars) }}
        run: ${{ github.workspace }}/scripts/dump_context.sh

      - run: terraform init
      - run: terraform validate

      - name: import bootstrap
        env:
          OIDC_ROLE_TO_ASSUME: ${{ vars.OIDC_ROLE_TO_ASSUME }}
        run: ../scripts/import_bootstrap.sh

      - name: terraform plan
        if: ${{ inputs.terraform_action == 'plan' }}
        run: |
          terraform plan -out=./tfplan.binary
          echo -e "\n::notice::Plan details.\n"

      - name: terraform plan destroy
        if: ${{ inputs.terraform_action == 'plan destroy' }}
        run: |
          terraform plan -destroy -out=./tfplan.binary
          echo -e "\n::notice::Plan destroy details.\n"

      - name: show plan summary
        if : ${{ inputs.terraform_action == 'plan' || inputs.terraform_action == 'plan destroy' }}
        run: ../scripts/show_plan_summary.sh

      - name: terraform apply
        if: ${{ inputs.terraform_action == 'apply' }}
        run: |
          set -o pipefail
          terraform apply -auto-approve | tee tfapply.out
          echo -e "\n::notice::Apply details.\n"

      - name: terraform destroy
        if: ${{ inputs.terraform_action == 'destroy' }}
        run: |
          set -o pipefail
          terraform apply -destroy -auto-approve | tee tfdestroy.out
          echo -e "\n::notice::Destroy details.\n"

      - name: show apply summary
        if: ${{ inputs.terraform_action == 'apply' || inputs.terraform_action == 'destroy' }}
        run: ../scripts/show_apply_summary.sh "${{ inputs.terraform_action }}"
